name: Python CI

#Triggers the workflow on any push to main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout the code from repositiorry
      - name: check out code
        uses: actions/checkout@v2

      # 2. cset up enviroment
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      # 4. Run test
      - name: Run tests
        run: pytest
